name: build-and-push-image
on:
  push:
    branches-ignore:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"
      - name: Setup Ko
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: europe-west3-docker.pkg.dev/itnderary/backend
      - run: |
          echo "${{ secrets.ARTIFACT_REGISTRY_TOKEN }}" | ko login europe-west3-docker.pkg.dev -u _json_key --password-stdin
          ko build
